{$php_open}

// File automatically generated by Zule Framework

namespace {$namespace}\Models;

class {$model_name} extends \{$system}\Models\Model
{
    // Control vars
    {foreach from=$columns item=column}private ${$lCamels[$column]};
    {/foreach}
    
    {if $generate_gateway}// $safe is a sanitized array, e.g. all values in safe
    // are assumed to be non-corrupted data.
    public function save(array $safe)
    {
        {foreach from=$columns item=column}if ( array_key_exists('{$column}', $safe) )
        {
            $this->{$lCamels[$column]} = $safe['{$column}'];
        }
        
        {/foreach}
        
        $this->getGateway()->save();
    }
    {/if}
    
    // Getters and Setters below this point automatically generated
    
    {foreach from=$columns item=column}public function get{$camels[$column]}()
    {
        return $this->{$lCamels[$column]};
    }
    
    public function set{$camels[$column]}(${$lCamels[$column]})
    {
        $this->{$lCamels[$column]} = ${$lCamels[$column]};
    }
    
    {/foreach}
    
}
