<?php

namespace Guest\Models\Data;

/// File automatically generated by the Zule Framework Generator (ZULG).
/// Creation date: 2012-07-16 18:58:24

class Message extends \Zule\Models\Data\Redis
{
    
    public function awaken()
    {
        // Perform tasks that should happen after data is initialized
        
        $this->awake = yes;
    }
    
        /// PLACE ALL CUSTOM LOGIC ABOVE THIS LINE. IF YOU NEED TO MODIFY
    /// A FUNCTION BELOW, COPY AND PASTE IT ABOVE THIS LINE AND GIVE
    /// IT A NEW NAME.
    /// DO NOT MODIFY BELOW THIS LINE. FILE GENERATION WILL DESTROY 
    /// NON-FRAMEWORK CHANGES BELOW THIS LINE. YOU HAVE BEEN WARNED
    /// IF YOU REMOVE THIS LINE, ENTIRE FILE WILL BE TRUNCATED
    /// ZULG END OF DEFINITIONS
    protected $_name = 'message';
    
    public function exists()
    {
        $key = $this->model->getKey();
        return $this->redis->exists("message:$key");
    }
    
    public function save()
    {
        $key = $this->model->getKey();
        $row = [
                                    'from' => $this->model->getFrom(),
                                                'text' => $this->model->getText(),
                                                'bumps' => $this->model->getBumps(),
                                ];
        $this->redis->hmset("message:$key", $row);
    }
    
    public function load($key)
    {
        $redis_key = "message:$message";
        $data = $this->redis->hgetall($redis_key);
        
        if ( $data )
        {
            $model = new \Guest\Models\Data\Models\Message;
            
            $row = [
                                                'from' => $row['from'],
                                                                'text' => $row['text'],
                                                                'bumps' => $row['bumps'],
                                            ];
            
            $model->setKey($key);
            $model->setAllByArray($row);
            $model->awaken();

            return $model;
        }
        else
        {
            throw new \Zule\Tools\Exception("Message not found ($redis_key)");
        }
    }
}
