{$open_php}

namespace {$namespace};

/// File automatically generated by the Zule Framework Generator (ZULG).
/// Creation date: {$impl_date}

class {$class_name} extends {$extend_path}
{
    
    public function awaken()
    {
        // Perform tasks that should happen after data is initialized
        
        $this->awake = yes;
    }
    
    