
    /// PLACE ALL CUSTOM LOGIC ABOVE THIS LINE. IF YOU NEED TO MODIFY
    /// A FUNCTION BELOW, COPY AND PASTE IT ABOVE THIS LINE AND GIVE
    /// IT A NEW NAME.
    /// DO NOT MODIFY BELOW THIS LINE. FILE GENERATION WILL DESTROY 
    /// NON-FRAMEWORK CHANGES BELOW THIS LINE. YOU HAVE BEEN WARNED
    /// IF YOU REMOVE THIS LINE, ENTIRE FILE WILL BE TRUNCATED
    /// ZULG END OF DEFINITIONS
