<?php

namespace Guest\Models;

/// File automatically generated by the Zule Framework Generator (ZULG).
/// Creation date: 2012-07-16 18:58:24

class User extends \Zule\Models\Model
{
    private $email;
    private $name;
    
    public function awaken()
    {
        // Perform tasks that should happen after data is initialized
        
        $this->awake = yes;
    }
    
    public function save(array $safe)
    {
        if ( array_key_exists('from', $safe) )
        {
            $this->from = $safe['from'];
        }
        
        if ( array_key_exists('text', $safe) )
        {
            $this->text = $safe['text'];
        }
        
        if ( array_key_exists('bumps', $safe) )
        {
            $this->bumps = $safe['bumps'];
        }
        
                
        $this->getGateway()->save();
    }
    
    public function getKey()
    {
        return $this->key;
    }
    
    public function setKey($key)
    {
        if ( !$this->awake )
        {
            $this->key = $key;
        }
        else
        {
            throw new \Zule\Tools\Exception(
                'Redis key "$key" can only be set when object is asleep.'
            );
        }
    }
    
    public function setAllByArray(array $inArray)
    {
        $this->from = $inArray['from'];
        $this->text = $inArray['text'];
        $this->bumps = $inArray['bumps'];
    }
    
    public function getFrom()
    {
        return $this->from;
    }
    
        
    public function getText()
    {
        return $this->text;
    }
    
        
    public function getBumps()
    {
        return $this->bumps;
    }
    
        
        
}
